### ISSUE TITLE
Command not working on windows system. 

### ISSUE THREAD

**Issue by NatnaelZeleke** [cyclosproject/ng-swagger-gen#122]
I was trying to generate services and models from a swagger link on windows but it doesn't work.  But the same command  works on Linux system.  The following error happens when i execute this command on windows.  

**node node_modules/.bin/ng-swagger-gen -i  swagger_url**

```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

```

**Comment by luisfpg** [comment]
Sorry, I don't use Windows, and I have nowhere to test it.
Patches welcome ;)

**Comment by Maxim-Mazurok** [comment]
@NatnaelZeleke you should run just `ng-swagger-gen -i swagger_url`
Because for Windows, there is `ng-swagger-gen.cmd`. So, command may be `node node_modules/.bin/ng-swagger-gen -i swagger_url`
So, there is no issue, I think we should close it.
