### ISSUE TITLE
ng-swagger-gen.js:710

### ISSUE THREAD

**Issue by houssamKasri** [cyclosproject/ng-swagger-gen#3]
C:\Users\hkasri\PhpstormProjects\aaaaa\angular-material\node_modules\.bin>ng-swagger-gen ../../swagger.json dir
C:\Users\hkasri\PhpstormProjects\aaaaa\angular-material\node_modules\ng-swagger-gen\ng-swagger-gen.js:710
        console.log("Ignoring " + name + "." + method
                                  ^

ReferenceError: name is not defined
    at processServices (C:\Users\hkasri\PhpstormProjects\aaaaa\angular-material\node_modules\ng-swagger-gen\ng-swagger-gen.js:710:35)
    at doGenerate (C:\Users\hkasri\PhpstormProjects\aaaaa\angular-material\node_modules\ng-swagger-gen\ng-swagger-gen.js:89:18)
    at fs.readFile (C:\Users\hkasri\PhpstormProjects\aaaaa\angular-material\node_modules\ng-swagger-gen\ng-swagger-gen.js:59:9)
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)

**Comment by luisfpg** [comment]
It is an error while handling the case of an operation with no / multiple tags.
It will be fixed so the generation doesn't stop.
However, ng-swagger-gen expects all operations to have a single tag.
If that's not the case, the operation is ignored.

**Comment by luisfpg** [comment]
With the release of 0.5.0, we no longer halt generation if an operation has no tags or multiple tags, or if it doesn't have an id.
So, this should be fixed.
